psoc4_load_library(
  NAME psoc4hal
  VERSION 0.5.0
)

set(PSOC4HAL_SOURCES
  ${PSOC4HAL_DIR}/include/cyhal.h
  ${PSOC4HAL_DIR}/include/cyhal_adc.h
  ${PSOC4HAL_DIR}/include/cyhal_clock.h
  ${PSOC4HAL_DIR}/include/cyhal_comp.h
  ${PSOC4HAL_DIR}/include/cyhal_crc.h
  ${PSOC4HAL_DIR}/include/cyhal_dma.h
  ${PSOC4HAL_DIR}/include/cyhal_ezi2c.h
  ${PSOC4HAL_DIR}/include/cyhal_flash.h
  ${PSOC4HAL_DIR}/include/cyhal_general_types.h
  ${PSOC4HAL_DIR}/include/cyhal_gpio.h
  ${PSOC4HAL_DIR}/include/cyhal_hwmgr.h
  ${PSOC4HAL_DIR}/include/cyhal_i2c.h
  ${PSOC4HAL_DIR}/include/cyhal_i2s.h
  ${PSOC4HAL_DIR}/include/cyhal_interconnect.h
  ${PSOC4HAL_DIR}/include/cyhal_lptimer.h
  ${PSOC4HAL_DIR}/include/cyhal_opamp.h
  ${PSOC4HAL_DIR}/include/cyhal_pwm.h
  ${PSOC4HAL_DIR}/include/cyhal_spi.h
  ${PSOC4HAL_DIR}/include/cyhal_syspm.h
  ${PSOC4HAL_DIR}/include/cyhal_system.h
  ${PSOC4HAL_DIR}/include/cyhal_timer.h
  ${PSOC4HAL_DIR}/include/cyhal_trng.h
  ${PSOC4HAL_DIR}/include/cyhal_uart.h
  ${PSOC4HAL_DIR}/include/cyhal_wdt.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/cyhal_clock_impl.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/cyhal_drivers.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/cyhal_gpio_impl.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/cyhal_hw_resources.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/cyhal_hw_types.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/cyhal_pin_package.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/cyhal_pwm_impl.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/cyhal_scb_common.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/cyhal_syspm_impl.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/cyhal_system_impl.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/cyhal_tcpwm_common.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/cyhal_timer_impl.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/cyhal_triggers.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/cyhal_utils.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4000s_20_ssop.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4000s_24_qfn.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4000s_25_wlcsp.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4000s_28_ssop_auto.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4000s_32_qfn.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4000s_32_tqfp.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4000s_40_qfn.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4000s_48_tqfp.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4100s_28_ssop_auto.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4100s_32_qfn.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4100s_35_wlcsp.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4100s_40_qfn.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4100s_40_qfn_auto.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4100s_44_tqfp.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4100s_48_tqfp.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4100smax_100_tqfp.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4100smax_48_tqfp.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4100smax_64_tqfp.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4100sp256kb_48_tqfp.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4100sp256kb_48_tqfp_mc.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4100sp256kb_64_tqfp.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4100sp256kb_64_tqfp_mc.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4100sp_40_qfn_2.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4100sp_44_tqfp.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4100sp_48_tqfp.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/pin_packages/cyhal_psoc4100sp_64_tqfp.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/triggers/cyhal_triggers_psoc4000s.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/triggers/cyhal_triggers_psoc4100s.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/triggers/cyhal_triggers_psoc4100smax.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/triggers/cyhal_triggers_psoc4100sp.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include/triggers/cyhal_triggers_psoc4100sp256kb.h
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/cyhal_clock.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/cyhal_ezi2c.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/cyhal_gpio.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/cyhal_hwmgr.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/cyhal_i2c.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/cyhal_interconnect.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/cyhal_pwm.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/cyhal_scb_common.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/cyhal_spi.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/cyhal_syspm.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/cyhal_system.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/cyhal_tcpwm_common.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/cyhal_timer.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/cyhal_uart.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/cyhal_utils.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/cyhal_wdt.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4000s_20_ssop.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4000s_24_qfn.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4000s_25_wlcsp.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4000s_28_ssop_auto.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4000s_32_qfn.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4000s_32_tqfp.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4000s_40_qfn.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4000s_48_tqfp.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4100s_28_ssop_auto.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4100s_32_qfn.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4100s_35_wlcsp.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4100s_40_qfn.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4100s_40_qfn_auto.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4100s_44_tqfp.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4100s_48_tqfp.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4100smax_100_tqfp.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4100smax_48_tqfp.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4100smax_64_tqfp.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4100sp256kb_48_tqfp.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4100sp256kb_48_tqfp_mc.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4100sp256kb_64_tqfp.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4100sp256kb_64_tqfp_mc.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4100sp_40_qfn_2.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4100sp_44_tqfp.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4100sp_48_tqfp.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/pin_packages/cyhal_psoc4100sp_64_tqfp.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/triggers/cyhal_triggers_psoc4000s.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/triggers/cyhal_triggers_psoc4100s.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/triggers/cyhal_triggers_psoc4100smax.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/triggers/cyhal_triggers_psoc4100sp.c
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/source/triggers/cyhal_triggers_psoc4100sp256kb.c
)
set(PSOC4HAL_INCLUDE_DIRS
  ${PSOC4HAL_DIR}/include
  ${PSOC4HAL_DIR}/COMPONENT_PSOC4HAL/include
)
set(PSOC4HAL_LINK_LIBRARIES
  psoc4pdl
)

add_library(psoc4hal STATIC EXCLUDE_FROM_ALL ${PSOC4HAL_SOURCES})
target_include_directories(psoc4pdl PUBLIC ${PSOC4HAL_INCLUDE_DIRS})
target_link_libraries(psoc4hal PUBLIC ${PSOC4HAL_LINK_LIBRARIES})
